[database]
connection_string = 'postgresql://postgres.bongcougnxgianszefdf:TvkL5Ogo5w0ZC9ST@aws-0-us-west-1.pooler.supabase.com:6543/postgres'


[connections.gsheets3]
spreadsheet = "https://docs.google.com/spreadsheets/d/18-Xzb2pzAg01c0uJnxcTZmu2vaZ45uAr1JFs60i8ThQ/edit?gid=0#gid=0"

# From your JSON key file
type = "service_account"
project_id = "repvar-bi"
private_key_id = "e19e4037e83cfa7769d6d5d24d16c79f44f98b28"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQClR7NAawMdxhv6\ni9Mbze7iJakG5bDbYBYppArIioToGxmmOP/j/hkkpV/qc0Y50U6mCKa1q6EautZg\n2HUlGavzx+CYcRqBh8Xpz1aXzIXhqF1mvZGcHRBOcS9dclUdrOdT30Uq+nWJTJyc\nSIfNO4kOHBGbMRqVzE2yiZcCd7tsfX87F2NzTJ5gy+voajWe1d27tvT9L6ITYuUl\noMU2+DvEEAMuMhInXUovwhrUtQeQ+HSGlvsBDss0tAZyMuQnmRjEjz3EIpZCF1DN\nyemjwy0Wb28t8cB6lIkDMfz9Prue4JFgeYRNg4FyxTpp65K43hhph8/4vZK5lcIW\nep3zVXwrAgMBAAECggEARuU4CwA8EHfrhW+XyNvvRXsRA1/gGmGfcBIo+/eK5gLF\n4Eqf3NygTVtQhsEWlPNmsIqSc+fgTZZqIZWHvjfCTenlOY5+Z6RlLRMeWjPFE9QD\n6G+VN2kyFuuu/P7varDBc3UYdsSDSTcfEFx+P/bzJaW9mZuZAztk8pnZOBpCv1ht\n6hga78q1gCP/2hfqMkxBQ7dg9NAsHYPUOzZjpQYwz5zRvygGP3eFlgDbcEFgwk+M\n+2dPRV7/HD2F5F2lHaTu7raoCbhRPpyif/4LwUncC1vU9mlZVWx/DtFtzy61GAvy\nIK/S1CKBminXyvndsFlsUClm7GMwOtkW3rPMkXSlFQKBgQDmv42c6qPVVS9kmhVR\nGRpNCzj2tCBusikinYOUL0+tidnXXUcq1l//cswXgw3JtGcOKqfXD/WvnGxAbGR4\n5OJzyYcYzvsSQWxw51LoY6YLGqPnO5T5hSDR4iwSQegq3H6jo0H+uR7lp9yEyhIo\n/tdkywEF5Zc/cu6c1/vzigmyFQKBgQC3XgvalBBiQrcm1/Kxka5UBFp9W2dHw2CC\nwNerJUP038gtruNqDiUChvRxTq+rb1mKuN+VsfWqRAQOQddZIZxMYsFOcspNBa6H\nptKxPvhJ+3fkpk5MzhX0Oztk7EyyKh6zw+3Lb8y2hgJQJGYakyKs9P3dzAteY+ep\n6S7EOedFPwKBgBo/if1il5Zp5UU9XdVm1J4U+7rcjJ/q9lDwuAoAQ8EK4FPmUXUn\nA66MQXkfOE9MjTiIU6VcNGdwlMPTUK6L4tKnBw4kZV0TQiGpvr2esEGtGx3voies\nJCqb3sWI578Qa/tzU8uFBWW8bZJRZjVxn9DgYtJn5oeaLFh9HTT769RtAoGBAJNP\ngKJnFQp7onwYPKce7DgfDztqNPzYHy6sEhcyZvfQ2BarS5OmLWFsXfCxUDufxwXF\nJAo037Gb1s5FYuX+NHzBUZ7eZVufVukvwlAW0I1O8rDEUl8tqUF+XGbl12/Cmsu8\nectX09RGsJEFzOlIjzD32QNYq0F3bWN5K9ME2aEtAoGAaIqgW+WYUPmzbTk4EkLl\nifolO/GaSpiTOM8IkOnW04UBIFl8Om2K4+5hMz6qSWVQGZFbG1OfgMI+C5LbgL7U\nKGcccZg/ztbRS+TvQl9f4cQ4TJT5qrY6tT7zrjTAuL79aZCMP1SZMcX7E3GWJ6GS\nw4zU5EAzznWPsfg+7cT2ta8=\n-----END PRIVATE KEY-----\n"
client_email = "repvar-bi-sheets@repvar-bi.iam.gserviceaccount.com"
client_id = "118240376647900516825"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "googleapis.com"


[connections.mysql]
dialect = "mysql"
host = "localhost"
port = 3306
database = "bije"
username = "root"
password = "root"
query = { charset = "utf8mb4" }
